{
 "title": "Spring Boot 监控",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(http_server_requests_seconds_count, job)"
    }
   },
   {
    "name": "tenantId",
    "label": "tenantId",
    "query": {
     "query": "label_values(api_requests_timer_seconds_sum,tenantId)"
    }
   },
   {
    "name": "uri",
    "label": "uri",
    "query": {
     "query": "label_values(http_server_requests_seconds_count,uri)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "请求总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"$job\", uri=~\"$uri\", uri!=\"/actuator/prometheus\"})"
    }
   ]
  },
  {
   "title": "请求调用量统计",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{job=\"$job\", uri!=\"/actuator/prometheus\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "请求平均耗时",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri)(http_server_requests_seconds_sum{job=\"$job\", uri=~\"$uri\"}) / sum by(uri)(http_server_requests_seconds_count{job=\"$job\", uri=~\"$uri\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "异常总数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"$job\", uri=~\"$uri\", exception!=\"none\"})"
    }
   ]
  },
  {
   "title": "2xx 请求百分比",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{job=\"$job\", uri=~\"$uri\", status=~\"2.*\", uri!=\"/actuator/prometheus\"}) / sum by(uri) (http_server_requests_seconds_count{job=\"$job\", uri=~\"$uri\", uri!=\"/actuator/prometheus\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "5xx 请求百分比",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{job=\"$job\", status=~\"5.*\", uri=~\"$uri\", uri!=\"/actuator/prometheus\"}) / sum by(uri) (http_server_requests_seconds_count{job=\"$job\", uri=~\"$uri\", uri!=\"/actuator/prometheus\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "非 2xx 请求百分比",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{job=\"$job\", status!~\"2.*\", uri=~\"$uri\", uri!=\"/actuator/prometheus\"}) / sum by(uri) (http_server_requests_seconds_count{job=\"$job\", uri=~\"$uri\", uri!=\"/actuator/prometheus\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "非 2xx 请求",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{job=\"$job\", status!~\"2.*\", uri=~\"$uri\", uri!=\"/actuator/prometheus\"}) / sum by(uri) (http_server_requests_seconds_count{job=\"$job\", uri=~\"$uri\", uri!=\"/actuator/prometheus\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(uri)(rate(http_server_requests_seconds_count{job=\"$job\", uri=~\"$uri\"}[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}